title: Mohamed Behery
url: "behery.github.io"
baseurl: "behery.github.io"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Home"
   link: "behery.github.io"
 - name: "Resume"
   link: "cv.pdf"
 - name: "Teaching"
   link: "behery.github.io/teaching"
 - name: "Projects"
   link: "behery.github.io/projects"
 - name: "Contact"
   link: "behery.github.io/contact"
